//
//  JobType.swift
//  TextValidator
//
//  Created by Alfian on 19/10/24.
//

enum JobType: String, CaseIterable {
    case BelumTidakBekerja = "BELUM/TIDAK BEKERJA"
    case MengurusRumahTangga = "MENGURUS RUMAH TANGGA"
    case PelajarMahasiswa = "PELAJAR/MAHASISWA"
    case Pensiunan = "PENSIUNAN"
    case PewagaiNegeriSipil = "PEGAWAI NEGERI SIPIL"
    case TentaraNasionalIndonesia = "TENTARA NASIONAL INDONESIA"
    case KepolisisanRI = "KEPOLISIAN RI"
    case Perdagangan = "PERDAGANGAN"
    case PetaniPekebun = "PETANI/PEKEBUN"
    case Peternak = "PETERNAK"
    case NelayanPerikanan = "NELAYAN/PERIKANAN"
    case Industri = "INDUSTRI"
    case Konstruksi = "KONSTRUKSI"
    case Transportasi = "TRANSPORTASI"
    case KaryawanSwasta = "KARYAWAN SWASTA"
    case KaryawanBUMN = "KARYAWAN BUMN"
    case KaryawanBUMD = "KARYAWAN BUMD"
    case KaryawanHonorer = "KARYAWAN HONORER"
    case BuruhHarianLepas = "BURUH HARIAN LEPAS"
    case BuruhTaniPerkebunan = "BURUH TANI/PERKEBUNAN"
    case BuruhNelayanPerikanan = "BURUH NELAYAN/PERIKANAN"
    case BuruhPeternakan = "BURUH PETERNAKAN"
    case PembantuRumahTangga = "PEMBANTU RUMAH TANGGA"
    case TukangCukur = "TUKANG CUKUR"
    case TukangListrik = "TUKANG LISTRIK"
    case TukangBatu = "TUKANG BATU"
    case TukangKayu = "TUKANG KAYU"
    case TukangSolSepatu = "TUKANG SOL SEPATU"
    case TukangLasPandaiBesi = "TUKANG LAS/PANDAI BESI"
    case TukangJahit = "TUKANG JAHIT"
    case TukangGigi = "TUKANG GIGI"
    case PenataRias = "PENATA RIAS"
    case PenataBusana = "PENATA BUSANA"
    case PenataRambut = "PENATA RAMBUT"
    case Mekanik = "MEKANIK"
    case Seniman = "SENIMAN"
    case Tabib = "TABIB"
    case Paraji = "PARAJI"
    case PerancangBusana = "PERANCANG BUSANA"
    case Penterjemah = "PENTERJEMAH"
    case ImamMasjid = "IMAM MESJID"
    case Pendeta = "PENDETA"
    case Pastor = "PASTOR"
    case Wartawan = "WARTAWAN"
    case UstadzMubaligh = "USTADZ/MUBALIGH"
    case JuruMasak = "JURU MASAK"
    case PromotorAcara = "PROMOTOR ACARA"
    case AnggotaDPRRI = "ANGGOTA DPR-RI"
    case AnggotaDPD = "ANGGOTA DPD"
    case AnggotaBPK = "ANGGOTA BPK"
    case Presiden = "PRESIDEN"
    case WakilPresiden = "WAKIL PRESIDEN"
    case AanggotaMahkamahKonstitusi = "ANGGOTA MAHKAMAH KONSTITUSI"
    case AnggotaKabinetKementrian = "ANGGOTA KABINET/KEMENTERIAN"
    case DutaBesar = "DUTA BESAR"
    case Gubernur = "GUBERNUR"
    case WakilGubernur = "WAKIL GUBERNUR"
    case Bupati = "BUPATI"
    case WakilBupati = "WAKIL BUPATI"
    case Walikota = "WALIKOTA"
    case WakilWalikota = "WAKIL WALIKOTA"
    case AnggotaDPRDProvinsi = "ANGGOTA DPRD PROVINSI"
    case AanggotaDPRDKabupatenKota = "ANGGOTA DPRD KABUPATEN/KOTA"
    case Dosen = "DOSEN"
    case Guru = "GURU"
    case Pilot = "PILOT"
    case Pengacara = "PENGACARA"
    case Notaris = "NOTARIS"
    case Arsitek = "ARSITEK"
    case Akuntan = "AKUNTAN"
    case Konsultan = "KONSULTAN"
    case Dokter = "DOKTER"
    case Bidan = "BIDAN"
    case Perawat = "PERAWAT"
    case Apoteker = "APOTEKER"
    case PsikiaterPsikolog = "PSIKIATER/PSIKOLOG"
    case PenyiarTelevisi = "PENYIAR TELEVISI"
    case PenyiarRadio = "PENYIAR RADIO"
    case Pelaut = "PELAUT"
    case Peneliti = "PENELITI"
    case Sopir = "SOPIR"
    case Pialang = "PIALANG"
    case Paranormal = "PARANORMAL"
    case Pedagang = "PEDAGANG"
    case PerangkatDesa = "PERANGKAT DESA"
    case KepalaDesa = "KEPALA DESA"
    case Biarawati = "BIARAWATI"
    case Wiraswasta = "WIRASWASTA"
    case Lainya = "LAINNYA"
}
